# /etc/mosquitto/mosquitto.conf

# Load additional configuration files
include_dir /etc/mosquitto/conf.d

# Persistence
persistence true
persistence_location /var/lib/mosquitto/

# Logging
log_dest stdout

# MQTT listener
listener 1883

# For testing only
allow_anonymous true
